### ISSUE TITLE
mcsmrt compatability with MacOS?

### ISSUE THREAD

**Issue by ChitongRao** [jpearl01/mcsmrt#2]
Hi,

I was wondering if the MCSMRT pipeline would be compatible with macOS Sierra, if I could use Ruby v2.2.1 or greater and meet all individual installation requirements?

Thanks,

Chitong

**Comment by jpearl01** [comment]
Hi Chitong,
We've never tested MCSMRT on macOS, but in theory it should be fine, if you can get the dependencies installed. I normally manage my ruby versions using [rvm](https://rvm.io/) which should work on macOS and allow you to install v2.2.1 

If you do get it working, I'd be very interested in hearing about it

~josh
