### ISSUE TITLE
Fatal error when using database in usearch

### ISSUE THREAD

**Issue by FFoQS90** [jpearl01/mcsmrt#3]
Hi,

I want to classify 16S rRNA gene sequences (Pacbio/ full length) using your database in usearch. 
When I run the sintax (or utax in V8.1) command i get the following error. 
```
usearch -sintax Pacbio_seqs.fasta -db 16sMicrobial_ncbi_lineage_reference_database.udb -strand both -sintax_cutoff 0.8

---Fatal error---
.udb magic4 0x55545831 should be 0x55444234

usearch8.1 -utax Pacbio_seqs.fasta -db 16sMicrobial_ncbi_lineage_reference_database.udb -strand both -alnout aln.txt

or for utax in version 8.1:
---Fatal error---
ReadStdioFile failed, attempted 29731733 bytes, read 25840504 bytes, errno=2
```

I believe that the errors mean that the headers in the database are not correctly formatted is that correct? 
However, I thought that the database already has the headers formatted as needed, so I am not sure what the problem is?

**Comment by jpearl01** [comment]
The errors you're getting for sintax are definitely related to both version and the algorithm used to create the database (i.e. this is a utax specific database and won't be compatible using the sintax). The database was made using usearch 8.1.1861 and so differences in the hashing are almost certainly not going to work between program versions.  i.e. using the binary (udb) version of the database will only work with v8.1.1861

This gets to the more troubling error you're seeing when using version 8.1.  At some point in the past we were able to successfully create a binary version of the database using the 64bit version, and then use the 32 bit version to classify the sequences (iirc).  The error you are seeing I can also replicate when I specifically use the 32bit version - so this is an issue when you attempt to use a database created with the 64bit version of usearch, and then attempt to use the 32bit version of usearch to do the classification. WHY that is an issue now, I don't know.  I was able to create a version of the database that will work with the 32bit version, using v8.1.1861 using our formatted ncbi fasta file.  Interestingly, the 32bit version of the database is also incompatible with the 64bit - I don't know why that would be, it can't be a memory thing, but possibly a hashing thing?  Regardless, we need to provide both 32bit versions of the database, and 64bit versions.  I'm in the process of doing some significant updates to the documentation of MCSMRT so I'll make sure to include this information. 

Here are links you can use to download the different versions of the database (including a sintax 32bit version, but please note: sintax is a very different algorithm than utax and the differences in version are likely not compatible with the current version of mcsmrt - but obviously feel free to classify your reads however you would like) 

[utax udb for version 8.1 32bit](https://www.dropbox.com/s/g5tjy7unezde1o3/16S_NCBI_32bit_utax8.1.1861.udb?dl=0)
[sintax udb for version 11.0 32bit](https://www.dropbox.com/s/y83tdjsrikj4zum/16S_NCBI_32bit_sintax11.0.667.udb?dl=0)
[16S NCBI database with correctly formatted headers to build your own utax/sintax databases](https://www.dropbox.com/s/kje22s4gdad2fkp/16S_NCBI_utax_and_sintax_formatted.fasta.gz?dl=0)

Thanks for checking out the software, I appreciate the feedback!  Please let me know if you have any more trouble.

~josh

**Comment by FFoQS90** [comment]
Thanks for the quick response! I tried the new files for the 32bit version and everything worked out fine.
Great to hear that you keep this updated.

**Comment by jpearl01** [comment]
Excellent, glad it worked out
