### ISSUE TITLE
Ruby environment without rvm

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jpearl01/mcsmrt#4]
Hi, sorry this is not really mcsmrt related issue, but I cannot run rvm on my machine (no root). Is it possible to install a ruby environment with conda (cannot find how to do this, but I think it is possible)? or prehaps install rvm locally? -Again I cannot install root rvm. The default ruby on my system does not have the gems required. Thanks,

T.

**Comment by jpearl01** [comment]
Sorry for the delayed response, you should be able to manage the ruby installations without needing to install rvm with root - one of the benefits of using it actually.  I think you might have figured this out by this point, but for future sake, if you follow the instructions here: https://rvm.io/rvm/install
you'll be able to install rvm and subsequently any ruby version you need as a non-root user.

~josh
